{
 "title": "Single Query Details (Prometheus)",
 "description": "For one query",
 "tags": [
  "pgwatch",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus Datasource", "query": "prometheus" },
   {
    "name": "dbname",
    "label": "Database",
    "query": {
     "query": "label_values(pgwatch_stat_statements_calls, dbname)"
    }
   },
   { "name": "queryid", "label": "Query ID" },
   {
    "name": "sql_text",
    "query": {
     "query": "label_values(pgwatch_stat_statements_total_time{dbname=\"$dbname\", queryid=\"$queryid\"}, query)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SQL", "type": "text", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 }, "options": { "content": "$sql_text" } },
  {
   "title": "Calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "calls/s" } },
   "targets": [
    {
     "alias": "calls",
     "expr": "rate(pgwatch_stat_statements_calls{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Execution time per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms/s" } },
   "targets": [
    {
     "alias": "avg_runtime",
     "expr": "rate(pgwatch_stat_statements_total_time{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Execution time per call",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "avg_runtime",
     "expr": "rate(pgwatch_stat_statements_total_time{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval]) / rate(pgwatch_stat_statements_calls{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Shared Buffers Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "sb_hit_ratio",
     "expr": "(rate(pgwatch_stat_statements_shared_blks_hit{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval]) * 100) \n/\n(\n  rate(pgwatch_stat_statements_shared_blks_hit{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval]) \n  + \n  rate(pgwatch_stat_statements_shared_blks_read{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval])\n)",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Shared Buffers Hit/Read per call",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(rate(pgwatch_stat_statements_shared_blks_hit{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval]) * 8192)\n/\nrate(pgwatch_stat_statements_calls{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "Shared Buffers bytes hit"
    },
    {
     "expr": "(rate(pgwatch_stat_statements_shared_blks_read{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval]) * 8192)\n/\nrate(pgwatch_stat_statements_calls{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "Shared Buffers bytes read"
    }
   ]
  },
  {
   "title": "Temp Bytes Read/Written per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "temp_blks_read",
     "expr": "rate(pgwatch_stat_statements_temp_blks_read{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval]) * 8192",
     "legendFormat": "Temp Bytes read"
    },
    {
     "alias": "temp_blks_written",
     "expr": "rate(pgwatch_stat_statements_temp_blks_written{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval]) * 8192",
     "legendFormat": "Temp Bytes written"
    }
   ]
  },
  {
   "title": "Temp Bytes Read/Written per call",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "temp_blks_read",
     "expr": "(rate(pgwatch_stat_statements_temp_blks_read{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval]) * 8192)\n/\nrate(pgwatch_stat_statements_calls{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "Temp Bytes read"
    },
    {
     "alias": "temp_blks_written",
     "expr": "(rate(pgwatch_stat_statements_temp_blks_written{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval]) * 8192)\n/\nrate(pgwatch_stat_statements_calls{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "Temp Bytes written"
    }
   ]
  },
  {
   "title": "Backend block Read/Write time",
   "type": "timeseries",
   "description": "FYI - blk_write_time can easily be 0 as normally changes happen only in the shared buffers and are written out by the checkpointer / background writer.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms/s" } },
   "targets": [
    {
     "alias": "blk_read_time",
     "expr": "rate(pgwatch_stat_statements_blk_read_time{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "Blk read time"
    },
    {
     "alias": "blk_write_time",
     "expr": "rate(pgwatch_stat_statements_blk_write_time{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "Blk write time"
    }
   ]
  },
  {
   "title": "% of total_time spent in direct IO",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "io_time_pct",
     "expr": "(\n  rate(pgwatch_stat_statements_blk_read_time{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval]) \n  + \n  rate(pgwatch_stat_statements_blk_write_time{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval])\n) * 100\n/ \nrate(pgwatch_stat_statements_total_time{dbname=\"$dbname\", queryid=\"$queryid\"}[$__rate_interval])",
     "legendFormat": "IO time %"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 40 },
   "options": {
    "content": "### Brought to you by\n\n[![Cybertec – The PostgreSQL Database Company](https://www.cybertec-postgresql.com/wp-content/uploads/2025/02/cybertec-logo-white-blue.svg)](https://www.cybertec-postgresql.com/en/)\n"
   }
  }
 ]
}